"""empty message

Revision ID: 1cbbb889f387
Revises: 5911b65cbdaa
Create Date: 2014-01-06 22:59:27.861863

"""

# revision identifiers, used by Alembic.
revision = '1cbbb889f387'
down_revision = '5911b65cbdaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lastid', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('last_read')
    ### end Alembic commands ###
