"""empty message

Revision ID: 1dd742ccd2ad
Revises: 435543b0e1df
Create Date: 2013-12-10 13:01:55.843553

"""

# revision identifiers, used by Alembic.
revision = '1dd742ccd2ad'
down_revision = '435543b0e1df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_registered', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registered_at')
    op.drop_column('users', 'is_registered')
    ### end Alembic commands ###
