"""empty message

Revision ID: 2ea3890d8e37
Revises: 45d6287ff912
Create Date: 2014-01-02 22:39:52.428200

"""

# revision identifiers, used by Alembic.
revision = '2ea3890d8e37'
down_revision = '45d6287ff912'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('greetings', sa.Column('is_friend', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('greetings', 'is_friend')
    ### end Alembic commands ###
