"""empty message

Revision ID: 342e7f24b593
Revises: 48b1eab24e67
Create Date: 2014-01-15 00:29:13.418573

"""

# revision identifiers, used by Alembic.
revision = '342e7f24b593'
down_revision = '48b1eab24e67'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('last_read', u'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('last_read', sa.Column(u'user_id', mysql.INTEGER(display_width=11), nullable=True))
    ### end Alembic commands ###
