"""empty message

Revision ID: 45d6287ff912
Revises: 1dd742ccd2ad
Create Date: 2013-12-15 19:02:03.565524

"""

# revision identifiers, used by Alembic.
revision = '45d6287ff912'
down_revision = '1dd742ccd2ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    ### end Alembic commands ###
