"""empty message

Revision ID: 5911b65cbdaa
Revises: 34993feb932
Create Date: 2014-01-06 22:40:54.391675

"""

# revision identifiers, used by Alembic.
revision = '5911b65cbdaa'
down_revision = '34993feb932'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read_at')
    ### end Alembic commands ###
